language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - boris.malensek@zalando.de
    on_success: never
    on_failure: always
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3eb93f2a0c2931a59d0d
    on_success: change
    on_failure: always
    on_start: never
script: "sbt clean coverage +test"
after_success:
  - "sbt coveralls"
  - bash <(curl -s https://codecov.io/bash)